name: "project_warehouse"
version: "1.0.0"

profile: "project_warehouse"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  project_warehouse:
    bronze:
      +materialized: table
    silver:
      +materialized: view
    gold:
      +materialized: table
