sources:
  - name: analytics
    schema: analytics
    database: DBT_DB
    tables:
      - name: data
        description: "Analytics consumer dataset from OpenDataBay"

models:
  - name: opendatabay_consumer
    description: "Bronze layer: Raw weekly sales data from OpenDataBay without transformation"
    columns:
      - name: STORE
        description: "Unique identifier for each store"
      - name: DATE
        description: "Date of the weekly sales record"
      - name: WEEKLY_SALES
        description: "Total sales for the week at the store"
      - name: HOLIDAY_FLAG
        description: "Indicator whether the week contains a holiday (1 = Holiday, 0 = Non-Holiday)"
      - name: TEMPERATURE
        description: "Average temperature for the week"
      - name: FUEL_PRICE
        description: "Average fuel price in the region during the week"
      - name: CPI
        description: "Consumer Price Index"
      - name: UNEMPLOYMENT
        description: "Unemployment rate"
